### ISSUE TITLE
Ensure updater can also setup default environment for skywire.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-updater#4]
## Context
Currently, `skywire-updater` only updates binaries, however it should also set up the default environments for the services it is updating.

## Tasks
- [ ] Change `update/skywire` to set up environment (default app configs and database locations).
- [ ] Add `update/skywire-updater` to update scripts.
- [ ] Add `update/skycoin` to setup environment (storage and exec options).
